// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.webgpuaccess.tentative.getTextureFormat.rgba8
// Description:getTextureFormat() returns RGBA8 on a typical context
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("getTextureFormat() returns RGBA8 on a typical context");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  _assertSame(ctx.getTextureFormat(), "rgba8unorm", "ctx.getTextureFormat()", "\"rgba8unorm\"");
  t.done();
});
done();
